patsy_data_root = "/Users/dsteelma/git/patsy-data/"
database = "/Users/dsteelma/Desktop/patsy-prange_test.db"

accessions_files = %w[
  data/accessions/prange/batches/pcb/pcb001.csv
  data/accessions/prange/batches/pcb/pcb002.csv
  data/accessions/prange/batches/pcb/pcb003.csv
  data/accessions/prange/batches/pcb/pcb004.csv
  data/accessions/prange/batches/pcb/pcb005.csv
  data/accessions/prange/batches/pcb/pcb006.csv
  data/accessions/prange/batches/pcb/pcb007.csv
  data/accessions/prange/batches/pcb/pcb008.csv
  data/accessions/prange/batches/pcb/pcb009.csv
  data/accessions/prange/batches/pcb/pcb010.csv
  data/accessions/prange/batches/pcb/pcb011.csv
  data/accessions/prange/batches/pcb/pcb012.csv
  data/accessions/prange/batches/pcb/pcb013.csv
  data/accessions/prange/batches/pcb/pcb014.csv
  data/accessions/prange/batches/pcb/pcb015.csv
  data/accessions/prange/batches/pcb/pcb016.csv
  data/accessions/prange/batches/pcb/pcb017.csv
  data/accessions/prange/batches/pcb/pcb018.csv
  data/accessions/prange/batches/pcb/pcb019.csv
  data/accessions/prange/batches/pcb/pcb020.csv
  data/accessions/prange/batches/pcb/pcb021.csv
  data/accessions/prange/batches/pcb/pcb022.csv
  data/accessions/prange/batches/pcb/pcb023.csv
  data/accessions/prange/batches/pcb/pcb024.csv
  data/accessions/prange/batches/pcb/pcb025.csv
  data/accessions/prange/batches/pcb/pcb026.csv
  data/accessions/prange/batches/pcb/pcb027.csv
  data/accessions/prange/batches/pcb/pcb028.csv
  data/accessions/prange/batches/pcb/pcb029.csv
  data/accessions/prange/batches/pcb/pcb030.csv
  data/accessions/prange/batches/pcb/pcb031.csv
  data/accessions/prange/batches/pcb/pcb032.csv
  data/accessions/prange/batches/pcb/pcb033.csv
  data/accessions/prange/batches/pcb/pcb034.csv
  data/accessions/prange/batches/pcb/pcb035.csv
  data/accessions/prange/batches/pcb/pcb036.csv
  data/accessions/prange/batches/pcb/pcb037.csv
  data/accessions/prange/batches/pcb/pcb038.csv
  data/accessions/prange/batches/pcb/pcb039.csv
  data/accessions/prange/batches/pcb/pcb040.csv
  data/accessions/prange/batches/pcb/pcb041.csv
  data/accessions/prange/batches/pcb/pcb042.csv
  data/accessions/prange/batches/pcb/pcb043.csv
  data/accessions/prange/batches/pcb/pcb044.csv
  data/accessions/prange/batches/pcb/pcb045.csv
  data/accessions/prange/batches/pcb/pcb046.csv
  data/accessions/prange/batches/pcb/pcb047.csv
  data/accessions/prange/batches/pcb/pcb048.csv
  data/accessions/prange/batches/pcb/pcb049.csv
  data/accessions/prange/batches/pcb/pcb050.csv
  data/accessions/prange/batches/pcb/pcb051.csv
  data/accessions/prange/batches/pcb/pcb052.csv
  data/accessions/prange/batches/pcb/pcb053.csv
  data/accessions/prange/batches/pcb/pcb054.csv
  data/accessions/prange/batches/pcb/pcb055.csv
  data/accessions/prange/batches/pcb/pcb056.csv
  data/accessions/prange/batches/pcb/pcb057.csv
  data/accessions/prange/batches/pcb/pcb058.csv
  data/accessions/prange/batches/pcb/pcb059.csv
  data/accessions/prange/batches/pcb/pcb060.csv
  data/accessions/prange/batches/pcb/pcb061.csv
  data/accessions/prange/batches/pcb/pcb062.csv
  data/accessions/prange/batches/pcb/pcb063.csv
  data/accessions/prange/batches/pcb/pcb064.csv
  data/accessions/prange/batches/pcb/pcb065.csv
  data/accessions/prange/batches/pcb/pcb066.csv
  data/accessions/prange/batches/pcb/pcb067.csv
  data/accessions/prange/batches/pcb/pcb068.csv
  data/accessions/prange/batches/pcb/pcb069.csv
  data/accessions/prange/batches/pcb/pcb070.csv
  data/accessions/prange/batches/pcb/pcb071.csv
  data/accessions/prange/batches/pcb/pcb073.csv
  data/accessions/prange/batches/pcb/pcb074.csv
  data/accessions/prange/batches/pcb/pcb075.csv
  data/accessions/prange/batches/pcb/pcb079.csv
  data/accessions/prange/batches/pcb/pcb080.csv
  data/accessions/prange/batches/pcb/pcb081.csv
  data/accessions/prange/batches/pcb/pcb082.csv
  data/accessions/prange/batches/pcb/pcb083.csv
  data/accessions/prange/batches/pcb/pcb084.csv
  data/accessions/prange/batches/pcb/pcb085.csv
  data/accessions/prange/batches/pcb/pcb087.csv
  data/accessions/prange/batches/pcb/pcb091.csv
  data/accessions/prange/batches/pcb/pcb092.csv
  data/accessions/prange/batches/pcb/pcb093.csv
  data/accessions/prange/batches/pcb/pcb094.csv
  data/accessions/prange/batches/pcb/pcb095.csv
  data/accessions/prange/batches/pcb/pcb096.csv
  data/accessions/prange/batches/pcb/pcb097.csv
  data/accessions/prange/batches/pcb/pcb098.csv
  data/accessions/prange/batches/pcb/pcb099.csv
  data/accessions/prange/batches/pcb/pcb100.csv
  data/accessions/prange/batches/pcb/pcb101.csv
  data/accessions/prange/batches/pcb/pcb102.csv
  data/accessions/prange/batches/pcb/pcb103.csv
  data/accessions/prange/batches/pcb/pcb104.csv
  data/accessions/prange/batches/pcb/pcb105.csv
  data/accessions/prange/batches/pcb/pcb106.csv
  data/accessions/prange/batches/pcb/pcb107.csv
  data/accessions/prange/batches/pcb/pcb108.csv
  data/accessions/prange/batches/pcb/pcb109.csv
  data/accessions/prange/batches/pcb/pcb110.csv
  data/accessions/prange/batches/pcb/pcb111.csv
  data/accessions/prange/batches/pcb/pcb112.csv
  data/accessions/prange/batches/pcb/pcb113.csv
  data/accessions/prange/batches/pcb/pcb114.csv
  data/accessions/prange/batches/pcb/pcb115.csv
  data/accessions/prange/batches/pcb/pcb116.csv
  data/accessions/prange/batches/pcb/pcb118.csv
  data/accessions/prange/batches/pcb/pcb119.csv
  data/accessions/prange/batches/pcb/pcb120.csv
  data/accessions/prange/batches/pcb/pcb121.csv
  data/accessions/prange/batches/pcb/pcb122.csv
  data/accessions/prange/batches/pcb/pcb123.csv
  data/accessions/prange/batches/pcb/pcb124.csv
  data/accessions/prange/batches/pcb/pcb125.csv
  data/accessions/prange/batches/pcb/pcb126.csv
  data/accessions/prange/batches/pcb/pcb127.csv
  data/accessions/prange/batches/pcb/pcb128.csv
  data/accessions/prange/batches/pcb/pcb129.csv
  data/accessions/prange/batches/pcb/pcb130.csv
  data/accessions/prange/batches/pcb/pcb131.csv
  data/accessions/prange/batches/pcb/pcb132.csv
  data/accessions/prange/batches/pcb/pcb133.csv
  data/accessions/prange/batches/pcb/pcb134.csv
  data/accessions/prange/batches/pcb/pcb135.csv
  data/accessions/prange/batches/pcb/pcb136.csv
  data/accessions/prange/batches/pcb/pcb137.csv
  data/accessions/prange/batches/pcb/pcb138.csv
  data/accessions/prange/batches/pcb/pcb139.csv
  data/accessions/prange/batches/pcb/pcb140.csv
  data/accessions/prange/batches/pcb/pcb141.csv
  data/accessions/prange/batches/pcb/pcb142.csv
  data/accessions/prange/batches/pcb/pcb143.csv
  data/accessions/prange/batches/pcb/pcb144.csv
  data/accessions/prange/batches/pcb/pcb145.csv
  data/accessions/prange/batches/pcb/pcb146.csv
  data/accessions/prange/batches/pgb/pgb001.csv
  data/accessions/prange/batches/pgb/pgb002.csv
  data/accessions/prange/batches/pgb/pgb003.csv
  data/accessions/prange/batches/pgb/pgb004.csv
  data/accessions/prange/batches/pgb/pgb005.csv
  data/accessions/prange/batches/pgb/pgb006.csv
  data/accessions/prange/batches/pgb/pgb007.csv
  data/accessions/prange/batches/pgb/pgb008.csv
  data/accessions/prange/batches/pgb/pgb009.csv
  data/accessions/prange/batches/pgb/pgb010.csv
  data/accessions/prange/batches/pgb/pgb011.csv
  data/accessions/prange/batches/pgb/pgb012.csv
  data/accessions/prange/batches/pgb/pgb013.csv
  data/accessions/prange/batches/pgb/pgb014.csv
  data/accessions/prange/batches/pgb/pgb015.csv
  data/accessions/prange/batches/pgb/pgb016.csv
  data/accessions/prange/batches/pgb/pgb017.csv
  data/accessions/prange/batches/pgb/pgb018.csv
  data/accessions/prange/batches/pgb/pgb019.csv
  data/accessions/prange/batches/pgb/pgb020.csv
  data/accessions/prange/batches/pgb/pgb021.csv
  data/accessions/prange/batches/pgb/pgb022.csv
  data/accessions/prange/batches/pgb/pgb023.csv
  data/accessions/prange/batches/pgb/pgb024.csv
  data/accessions/prange/batches/pgb/pgb025.csv
  data/accessions/prange/batches/pgb/pgb026.csv
  data/accessions/prange/batches/pgb/pgb027.csv
  data/accessions/prange/batches/pgb/pgb028.csv
  data/accessions/prange/batches/pgb/pgb029.csv
  data/accessions/prange/batches/pgb/pgb030.csv
  data/accessions/prange/batches/pgb/pgb031.csv
  data/accessions/prange/batches/pgb/pgb032.csv
  data/accessions/prange/batches/pgb/pgb033.csv
  data/accessions/prange/batches/pgb/pgb034.csv
  data/accessions/prange/batches/pgb/pgb035.csv
  data/accessions/prange/batches/pgb/pgb036.csv
  data/accessions/prange/batches/pgb/pgb037.csv
  data/accessions/prange/batches/pgb/pgb038.csv
  data/accessions/prange/batches/pgb/pgb039.csv
  data/accessions/prange/batches/pgb/pgb040.csv
  data/accessions/prange/batches/pgb/pgb041.csv
  data/accessions/prange/batches/pgb/pgb042.csv
  data/accessions/prange/batches/pgb/pgb043.csv
  data/accessions/prange/batches/pgb/pgb044.csv
  data/accessions/prange/batches/pgb/pgb045.csv
  data/accessions/prange/batches/pgb/pgb046.csv
  data/accessions/prange/batches/pgb/pgb047.csv
  data/accessions/prange/batches/pgb/pgb048.csv
  data/accessions/prange/batches/pgb/pgb049.csv
  data/accessions/prange/batches/pgb/pgb050.csv
  data/accessions/prange/batches/pgb/pgb051.csv
  data/accessions/prange/batches/pgb/pgb052.csv
  data/accessions/prange/batches/pgb/pgb053.csv
  data/accessions/prange/batches/pgb/pgb054.csv
  data/accessions/prange/batches/pgb/pgb055.csv
  data/accessions/prange/batches/pgb/pgb056.csv
  data/accessions/prange/batches/pgb/pgb057.csv
  data/accessions/prange/batches/pgb/pgb058.csv
  data/accessions/prange/batches/pgb/pgb059.csv
  data/accessions/prange/batches/pgb/pgb060.csv
  data/accessions/prange/batches/pgb/pgb061.csv
  data/accessions/prange/batches/pgb/pgb062.csv
  data/accessions/prange/batches/pgb/pgb063.csv
  data/accessions/prange/batches/pgb/pgb064.csv
  data/accessions/prange/batches/pgb/pgb065.csv
  data/accessions/prange/batches/pgb/pgb066.csv
  data/accessions/prange/batches/pgb/pgb067.csv
  data/accessions/prange/batches/pgb/pgb068.csv
  data/accessions/prange/batches/pgb/pgb069.csv
  data/accessions/prange/batches/pgb/pgb070.csv
  data/accessions/prange/batches/pgb/pgb071.csv
  data/accessions/prange/batches/pgb/pgb072.csv
  data/accessions/prange/batches/pgb/pgb073.csv
  data/accessions/prange/batches/pgb/pgb074.csv
  data/accessions/prange/batches/pgb/pgb075.csv
  data/accessions/prange/batches/pgb/pgb076.csv
  data/accessions/prange/batches/pgb/pgb077.csv
  data/accessions/prange/batches/pgb/pgb078.csv
  data/accessions/prange/batches/pgb/pgb079.csv
  data/accessions/prange/batches/pgb/pgb080.csv
  data/accessions/prange/batches/pgb/pgb081.csv
  data/accessions/prange/batches/pgb/pgb082.csv
  data/accessions/prange/batches/pgb/pgb083.csv
  data/accessions/prange/batches/pgb/pgb084.csv
  data/accessions/prange/batches/pgb/pgb085.csv
  data/accessions/prange/batches/pgb/pgb086.csv
  data/accessions/prange/batches/pgb/pgb087.csv
  data/accessions/prange/batches/pgb/pgb089.csv
  data/accessions/prange/batches/pgb/pgb090.csv
  data/accessions/prange/batches/pgb/pgb091.csv
  data/accessions/prange/batches/pgb/pgb092.csv
  data/accessions/prange/batches/pgb/pgb093.csv
  data/accessions/prange/batches/pgb/pgb094.csv
  data/accessions/prange/batches/pgb/pgb095.csv
  data/accessions/prange/batches/pgb/pgb096.csv
  data/accessions/prange/batches/pgb/pgb097.csv
  data/accessions/prange/batches/pgb/pgb098.csv
  data/accessions/prange/batches/pgb/pgb099.csv
  data/accessions/prange/batches/pgb/pgb100.csv
  data/accessions/prange/batches/pgb/pgb101.csv
  data/accessions/prange/batches/pgb/pgb102.csv
  data/accessions/prange/batches/pgb/pgb103.csv
  data/accessions/prange/batches/pgb/pgb122.csv
  data/accessions/prange/batches/pgb/pgb123.csv
  data/accessions/prange/batches/pgb/pgb124.csv
  data/accessions/prange/batches/pgb/pgb125.csv
  data/accessions/prange/batches/pgb/pgb126.csv
  data/accessions/prange/batches/pgb/pgb127.csv
  data/accessions/prange/batches/pgb/pgb128.csv
  data/accessions/prange/batches/pgb/pgb129.csv
  data/accessions/prange/batches/pgb/pgb130.csv
  data/accessions/prange/batches/pgb/pgb131.csv
  data/accessions/prange/batches/pgb/pgb132.csv
  data/accessions/prange/batches/pgb/pgb133.csv
  data/accessions/prange/batches/pgb/pgb134.csv
  data/accessions/prange/batches/pgb/pgb135.csv
  data/accessions/prange/batches/pgb/pgb136.csv
  data/accessions/prange/batches/pgb/pgb137.csv
  data/accessions/prange/batches/pgb/pgb138.csv
  data/accessions/prange/batches/pgb/pgb139.csv
  data/accessions/prange/batches/pgb/pgb140.csv
  data/accessions/prange/batches/pgb/pgb141.csv
  data/accessions/prange/batches/pgb/pgb142.csv
  data/accessions/prange/batches/pgb/pgb143.csv
  data/accessions/prange/batches/pgb/pgb144.csv
  data/accessions/prange/batches/pgb/pgb145.csv
  data/accessions/prange/batches/pgb/pgb146.csv
  data/accessions/prange/batches/pgb/pgb147.csv
  data/accessions/prange/batches/pgb/pgb148.csv
  data/accessions/prange/batches/pgb/pgb149.csv
  data/accessions/prange/batches/pgb/pgb150.csv
  data/accessions/prange/batches/pgb/pgb151.csv
  data/accessions/prange/batches/pgb/pgb152.csv
  data/accessions/prange/batches/pgb/pgb153.csv
  data/accessions/prange/batches/pgb/pgb154.csv
  data/accessions/prange/batches/pgb/pgb155.csv
  data/accessions/prange/batches/pgb/pgb156.csv
  data/accessions/prange/batches/pgb/pgb157.csv
  data/accessions/prange/batches/pgb/pgb158.csv
  data/accessions/prange/batches/pgb/pgb159.csv
  data/accessions/prange/batches/pgb/pgb160.csv
  data/accessions/prange/batches/pgb/pgb161.csv
  data/accessions/prange/batches/pgb/pgb162.csv
  data/accessions/prange/batches/pgb/pgb163.csv
  data/accessions/prange/batches/pgb/pgb164.csv
  data/accessions/prange/batches/pgb/pgb165.csv
  data/accessions/prange/batches/pgb/pgb166.csv
  data/accessions/prange/batches/pgb/pgb167.csv
  data/accessions/prange/batches/pgb/pgb168.csv
  data/accessions/prange/batches/pgb/pgb169.csv
  data/accessions/prange/batches/pgb/pgb170.csv
  data/accessions/prange/batches/pgb/pgb171.csv
  data/accessions/prange/batches/pgb/pgb172.csv
  data/accessions/prange/batches/pgb/pgb173.csv
  data/accessions/prange/batches/pgb/pgb174.csv
  data/accessions/prange/batches/pgb/pgb175.csv
  data/accessions/prange/batches/pgb/pgb176.csv
  data/accessions/prange/batches/pgb/pgb177.csv
  data/accessions/prange/batches/pgb/pgb178.csv
  data/accessions/prange/batches/pgb/pgb179.csv
  data/accessions/prange/batches/pgb/pgb180.csv
  data/accessions/prange/batches/pgb/pgb181.csv
  data/accessions/prange/batches/pgb/pgb182.csv
  data/accessions/prange/batches/pgb/pgb183.csv
  data/accessions/prange/batches/pgb/pgb184.csv
  data/accessions/prange/batches/pgb/pgb185.csv
  data/accessions/prange/batches/pgb/pgb186.csv
  data/accessions/prange/batches/pgb/pgb187.csv
  data/accessions/prange/batches/pgb/pgb188.csv
  data/accessions/prange/batches/pgb/pgb189.csv
  data/accessions/prange/batches/pgb/pgb190.csv
  data/accessions/prange/batches/pgb/pgb191.csv
  data/accessions/prange/batches/pgb/pgb192.csv
  data/accessions/prange/batches/pgb/pgb193.csv
  data/accessions/prange/batches/pgb/pgb194.csv
  data/accessions/prange/batches/pgb/pgb195.csv
  data/accessions/prange/batches/pgb/pgb196.csv
  data/accessions/prange/batches/pgb/pgb197.csv
  data/accessions/prange/batches/pgb/pgb198.csv
  data/accessions/prange/batches/pgb/pgb199.csv
  data/accessions/prange/batches/pgb/pgb200.csv
  data/accessions/prange/batches/pgb/pgb201.csv
  data/accessions/prange/batches/pgb/pgb202.csv
  data/accessions/prange/batches/pgb/pgb203.csv
  data/accessions/prange/batches/pgb/pgb204.csv
  data/accessions/prange/batches/pgb/pgb205.csv
  data/accessions/prange/batches/pgb/pgb206.csv
  data/accessions/prange/batches/pgb/pgb207.csv
  data/accessions/prange/batches/pgb/pgb208.csv
  data/accessions/prange/batches/pgb/pgb209.csv
  data/accessions/prange/batches/pgb/pgb210.csv
  data/accessions/prange/batches/pgb/pgb211.csv
  data/accessions/prange/batches/pgb/pgb212.csv
  data/accessions/prange/batches/pgb/pgb213.csv
  data/accessions/prange/batches/pgb/pgb214.csv
  data/accessions/prange/batches/pgb/pgb215.csv
  data/accessions/prange/batches/pgb/pgb216.csv
  data/accessions/prange/batches/pgb/pgb217.csv
  data/accessions/prange/batches/pgb/pgb218.csv
  data/accessions/prange/batches/pgb/pgb219.csv
  data/accessions/prange/batches/pgb/pgb220.csv
  data/accessions/prange/batches/pgb/pgb221.csv
  data/accessions/prange/batches/pgb/pgb222.csv
  data/accessions/prange/batches/pgb/pgb223.csv
  data/accessions/prange/batches/pgb/pgb224.csv
  data/accessions/prange/batches/pgb/pgb225.csv
  data/accessions/prange/batches/pgb/pgb226.csv
  data/accessions/prange/batches/pgb/pgb227.csv
  data/accessions/prange/batches/pgb/pgb228.csv
  data/accessions/prange/batches/pgb/pgb229.csv
  data/accessions/prange/batches/pgb/pgb230.csv
  data/accessions/prange/batches/pgb/pgb231.csv
  data/accessions/prange/batches/pgb/pgb232.csv
  data/accessions/prange/batches/pgb/pgb233.csv
  data/accessions/prange/batches/pgb/pgb234.csv
  data/accessions/prange/batches/pgb/pgb235.csv
  data/accessions/prange/batches/pgb/pgb236.csv
]

accessions_files.each do |file|
  full_file_path = patsy_data_root + file
  puts "echo #{file}"
  puts "time python3 -m patsy --database #{database} accessions --source #{full_file_path}"
end